interpolationfactor = 100e6/fs;

tx = comm.SDRuTransmitter(...
              'Platform','N200/N210/USRP2', ...
              'IPAddress','192.168.10.2', ...
              'CenterFrequency',0, ...
              'EnableBurstMode', true,...
              'NumFramesInBurst', numburst,...
              'InterpolationFactor',interpolationfactor);